### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by zcharef** [callmenikk/react-simplified-player#2]
Hello,

I know that setting `"type":"module"` in `package.json` solves this problem but my current stack (React with Remix) prefers not using `"type":"module"`.
How can I make your library work without setting this in my NodeJS config ?

Kindly,
Sl4yZ

**Comment by 8spw** [comment]
Hello

Thank you for opening issue and let me know about this problem
Sadly I've not tested my audio player on other react libraries such as [next](https://nextjs.org/) or [remix](https://remix.run/)

I installed Remix and my package and error really appears, but I've never had experience with this library

I will keep this issue open until someone won't come up how to solve this problem

Thanks
